### PR TITLE
Adding title tag to SWI Prolog homepage.

### PR DESCRIPTION
**Pull request by eazar001**
I just added `<title>SWI Prolog</title>` to the head tag in `index.hom`.

### CODE REVIEW

**Comment by eazar001** [comment]
I just added `<title>SWI Prolog</title>` to the head tag in `index.hom`.

**Comment by JanWielemaker** [comment]
This seems to be only  a submodule update?  Where is the real stuff?

**Comment by eazar001** [comment]
Hrmm, I have no idea why no changes got pushed. I pushed the changes in `www`, and for some reason my changes just dissapeared =\.

**Comment by JanWielemaker** [comment]
I guess they in some clone ...  You need to make a pull request for www.  Do not bother about the
main repo.  I'll do that.

**Comment by eazar001** [comment]
Sorry about that, I made a patch on `plweb-www`, straight from github

**Pull request closed without merging**
